services:
  postgres:
    container_name: rh_management_postgres
    image: postgres
    environment:
      POSTGRES_USER: mbacke
      POSTGRES_PASSWORD: mbacke
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: rh_management
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  maildev:
    container_name: rh_management_maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped

volumes:
  postgres:
    driver: local