spring:
  config:
    import: classpath:application-springdoc.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/rh_management
    username: mbacke
    password: mbacke
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    security:
      jwt:
        secret-key: EzlKRzeO3KNOmxBKbrpUdaPrqtl0JAZbEUfQX798k0A=
        expiration: 86400000
    file:
      uploads:
        photos-output-path: ./uploads
  servlet:
    multipart:
      max-file-size: 10485760  # 10MB
      allowed-mime-types:
        diploma:
          - application/pdf
          - application/vnd.openxmlformats-officedocument.wordprocessingml.document
        identity:
          - application/pdf
          - image/jpeg
          - image/png
        cv:
          - application/pdf
          - application/vnd.openxmlformats-officedocument.wordprocessingml.document


server:
  port: 8088