springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  packages-to-scan: sn.bmbacke.rh.controller
  show-actuator: false
  default-produces-media-type: application/json
